### ISSUE TITLE
Error: unable to find correct codec -> premature end (~0%)

### ISSUE THREAD

**Issue by xdli16** [anthwlock/untrunc#51] opened 2020-06-02 12:58 UTC
Info: version '71d1a65' using ffmpeg '3.3.4'
Info: reading ok.mp4
Info: parsing healthy moov atom ...
Composition time offset atom found. Out of order samples possible.

Info: reading mdat from truncated file ...
Error: unable to find correct codec -> premature end (~0%)
       try '-s' to skip unknown sequences

Warning: guessed frame durations of 'mp4a' will probably be wrong!
Warning: guessed frame durations of 'avc1' will probably be wrong!
Info: Found 0 packets ( mp4a: 0 avc1: 0 avc1-keyframes: 0 )
Info: Duration of mp4a:  (0 ms)
Info: Duration of avc1:  (0 ms)
Info: pruned empty 'mp4a' track
Info: pruned empty 'avc1' track
Info: saving no.mp4_fixed.mp4

**Comment by xdli16** [comment] 2020-06-02 12:59
I repair videos on Windows 10

**Comment by anthwlock** [comment] 2020-06-02 14:51
Make sure that `no.mp4` actually contains some data (by using hexeditor).
If so, please send me the flies (healthy+broken).

<details>
  <summary>How to upload</summary>

  https://wetransfer.com/ offers hosting <2GB files for 7days, without registration.
  If your files are larger, `untrunc -sh file.mp4` lets you extract the first 200MB.
  Either post the resulting link here, or send me an email.
</details>

**Comment by xdli16** [comment] 2020-06-03 07:20
broken video
https://send.firefox.com/download/3435e58b19ddedcf/#XcBGvd1SM2N_s4PiawlK9w
healthy video
https://send.firefox.com/download/69b3df691c456d40/#f6y_LVdtCPXXajygGKE8mQ

**Comment by anthwlock** [comment] 2020-06-03 17:44
What software did you used to create those files?
It looks like metadata got packed into avc1 samples..
Do you know something about Hi3518?

**Comment by anthwlock** [comment] 2020-06-03 18:42
Btw, the download of the broken 2.1GB file stops at 1.1GB. I tried multiple times and with different browsers.
But 1.1GB is probably enough anyway.

**Comment by xdli16** [comment] 2020-06-04 05:46
I use ffmpeg to record m3u8 live link，like
ffmpeg -i "http://xxx.m3u8" -vcodec copy -acodec copy -absf aac_adtstoasc "xxx.mp4"
I don't know HI3518.

**Comment by xdli16** [comment] 2020-06-04 05:57
I uploaded the broken video files again. This time, I compressed them into multiple compressed packages. If you need, you can download them again
https://send.firefox.com/download/06a198da8e19ed01/#OeI7OW2oNO6ztQjEg8fBNg
https://send.firefox.com/download/69982cfa1afb86e3/#cJ2koXa_OI0OK_Y82uohDA
https://send.firefox.com/download/ed62abaeeb109128/#UUanGayDSUgYu8AySNbS_g

**Comment by anthwlock** [comment] 2020-06-04 14:18
Just to make sure.. is the following md5sum correct?
a984f3ad141cccdaef5e850e6d96897c  no.mp4

**Comment by xdli16** [comment] 2020-06-05 14:06
a984f3ad141cccdaef5e850e6d96897c no.mp4

**Comment by anthwlock** [comment] 2020-06-06 16:08
The metadata was packed in nal-units with nal_type=31, fixed with 907fbb59435b96e5c77a90894f1206ec1058f8d7.

Additionally ffmpeg3.4+ failed to decode some mp4a samples, because internal decoder state was not reset after 'gaps' in the audio-stream. These gaps may be caused by network transmission errors. This got fixed with 56aee28f1edf686abaefd31f295130bebd2c9cf1.

**Tip**
When using ffmpeg you can avoid corrupt files by using `-f mpegts`.
This will create `.ts` instead of `.mp4`.
It also allows you to watch the stream while downloading.
Later you can use `ffmpeg -i file.ts -c copy file.mp4`.

**Closed** 2020-06-23 16:16 UTC
